### PR TITLE
Rearrange the documentation structure in the README and add additional information

### PR DESCRIPTION
**Pull request by Exairnous**
Generally improve the documentation with a lot more details and give it a more linear structure.
Convert the reference about this not being a production ready setup to an important note so that it shows clearly in GitHub.
Consolidate all of the prerequisites into their own section at the beginning of the document.
Add notes and tips on things to expect, operating system specific hints, etc..
Add a high level overview of how to set up Hubs Compose initially.
Expand the usage section to be clearer about how to start/stop Hubs Compose and where you go to correctly access the different parts of Hubs.
Improve the documentation of the orchestration commands and add additional system commands that can increase their scope, plus more advanced usage examples.
Add a section detailing how to sign into Hubs/Reticulum.
Clarify how to promote an account to admin.
Add a section detailing useful docker commands.
Expand and rearrange the troubleshooting section with gotchas, expected things to watch out for, etc..
Add instructions for clearing local storage, and hard refreshing a page i.e. clearing its cache.

Some of the changes in #59 are expected to be added in on top of this PR.

### CODE REVIEW

**Comment by Exairnous** [comment]
@DougReeder, @hrithikwins, @Heather-Elizabeth-Dodds I would appreciate your review, suggestions, etc. :)

**Comment by Exairnous** [comment]
@mikemorran and @keianhzo, you're welcome to weigh in on this as well.

**Comment by Heather-Elizabeth-Dodds** [comment]
> @DougReeder, @hrithikwins, @Heather-Elizabeth-Dodds I would appreciate your review, suggestions, etc. :)

Is there a typo in line 18? Should it be Homebrew?

I'm not reviewing the actual commands, but I've heard many of these specific suggestions before. Pacing and word choice looks good. I suspect this README will need a few add-ons later, but as of today, they look good to launch to me.

**Review by DougReeder — APPROVED** [review]
This looks good to me; it should make it much easier for new developers.

**Comment by DougReeder** [comment]
The changes look good to me.

**Comment by Exairnous** [comment]
@Heather-Elizabeth-Dodds @DougReeder Thanks for looking this over and approving it.  I'm merging it now.

**Pull request merged**
